### ISSUE TITLE
Can you provide a demo for cpu multiplayer video pose estimation

### ISSUE THREAD

**Issue by Deep-learning999** [luminxu/ViPNAS#11]
Can you provide a demo of cpu multi-person video attitude estimation, I want to see the fps and attitude estimation effect

**Comment by jin-s13** [comment]
Since ViPNAS has been integrated into MMPose. You may checkout https://github.com/open-mmlab/mmpose for demo.

**Comment by Deep-learning999** [comment]
Which demo is the real-time video webcam under cpu, is there a link to the demo in mmpose?

**Comment by Deep-learning999** [comment]
already found thanks
