### ISSUE TITLE
ONNX transfer problem

### ISSUE THREAD

**Issue by zeckireck** [luminxu/ViPNAS#12]
Hello, our script does not support the case that convtranpose group is greater than 1. How can we turn it into the case that each group is equal to 1?

**Comment by luminxu** [comment]
If you do not want to use deconvolutional layers with the group number greater than 1, you may try the backbone searched by ViPNAS (e.g. [ViPNAS_ResNet](https://github.com/luminxu/ViPNAS/blob/main/mmpose/models/backbones/vipnas_resnet.py#L342) following [s_vipnas_res50_coco_256x192.py](https://github.com/luminxu/ViPNAS/blob/main/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/s_vipnas_res50_coco_256x192.py#L43)), and apply the [TopdownHeatmapSimpleHead](https://github.com/luminxu/ViPNAS/blob/main/mmpose/models/heads/topdown_heatmap_simple_head.py#L15) as the keypoint_head following [SimpleBaseline](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py#L35). Make sure that the [in_channels](https://github.com/open-mmlab/mmpose/blob/master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192.py#L37) of keypoint_head should be consistent with the output_channels of backbone (e.g. 608 for S-ViPNAS-Res50).

**Comment by luminxu** [comment]
Also, if you still want to use [ViPNASHeatmapSimpleHead](https://github.com/open-mmlab/mmpose/blob/e7c7cadbbaf70f8080c093dc2910cd947a2ef6d6/mmpose/models/heads/vipnas_heatmap_simple_head.py#L16), you can set [num_deconv_groups](https://github.com/open-mmlab/mmpose/blob/e7c7cadbbaf70f8080c093dc2910cd947a2ef6d6/mmpose/models/heads/vipnas_heatmap_simple_head.py#L58) to be (1, 1, 1). No matter which one you choose, please retrain the new model and verify whether the performance satisfies your needs.

**Comment by zeckireck** [comment]
are these  factors (num_deconv_layers, num_deconv_filters, num_deconv_kernels) need to be modified?

**Comment by zeckireck** [comment]
or only change [num_deconv_groups](https://github.com/open-mmlab/mmpose/blob/e7c7cadbbaf70f8080c093dc2910cd947a2ef6d6/mmpose/models/heads/vipnas_heatmap_simple_head.py#L58) to be (1, 1, 1)

**Comment by luminxu** [comment]
You may try to change ``num_deconv_groups`` only. As it is no longer the keypoint head searched by ViPNAS, you should verify the accuracy under this setting. If necessary, you can also change other arguments.

**Comment by zeckireck** [comment]
Why are there 2 inferences here? Just to infer for once, can't it? Will there be a big impact on accuracy and confidence?[https://github.com/luminxu/ViPNAS/blob/56a0630efee9d36595c0f5d3268553f273d35ad3/mmpose/models/detectors/top_down.py#L184](url)

**Comment by luminxu** [comment]
``Flip Test`` is a common test-time technique for more robust prediction, which empirically introduces around 1% AP improvement. If you care more about the inference speed, you can turn it off in the [configuration](https://github.com/luminxu/ViPNAS/blob/56a0630efee9d36595c0f5d3268553f273d35ad3/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/s_vipnas_res50_coco_256x192.py#L51).

**Comment by zeckireck** [comment]
As for resnet50, do you know where this operator is in the code? Our hardware only supports the case where the divisor of the div operator is constant。
![image](https://user-images.githubusercontent.com/81000191/174972514-067e290c-1681-4e20-abdd-dd63b94e2dd2.png)
![image](https://user-images.githubusercontent.com/81000191/174973189-19e9e366-e818-4b0a-89ac-3cf127de1ee7.png)

**Comment by luminxu** [comment]
I cannot recognize the exact operators according to the figures. Also, I am not sure when the problem happens, e.g., instantiation (I guess so), initialization, or inference. According to your description, you may check [this line](https://github.com/luminxu/ViPNAS/blob/main/mmpose/models/backbones/vipnas_resnet.py#L115).

**Comment by zeckireck** [comment]
Is there any way to set out_channels to a fixed value?https://github.com/luminxu/ViPNAS/blob/main/mmpose/models/backbones/vipnas_resnet.py#L115

**Comment by zeckireck** [comment]
What is this attention used for?[https://github.com/luminxu/ViPNAS/blob/main/mmpose/models/backbones/vipnas_resnet.py#L115](url)is it necessary？

**Comment by luminxu** [comment]
Whether to use attention module is included in search spaces and is searched for better pose estimation performance. Please refer to our [paper](https://arxiv.org/abs/2105.10154) for more details.

**Comment by zeckireck** [comment]
[https://github.com/luminxu/ViPNAS/blob/main/mmpose/models/backbones/vipnas_resnet.py#L115](https://github.com/luminxu/ViPNAS/issues/url). Why do we need 16/outchannels here? only to use 1/16,cant it?
