### ISSUE TITLE
Video training data

### ISSUE THREAD

**Issue by garg-7** [luminxu/ViPNAS#4]
Hi,
I was going through the paper that this repository implements. The architecture diagram shows an interrelation between frames of a clip, however, in the repository I was unable to find a way to train the model using video clips or a bunch of consecutive frames. Could you please direct me to such a thing if I am missing it?

Thanks

**Comment by luminxu** [comment]
Thanks for your interest in our work. The figure in the paper shows the architecture of T-ViPNAS, which contains the temporal connections. Currently, we just reimplement S-ViPNAS, which is a image-based pose estimator, based on MMPose. Thus, training on videos has not been included in the repository.
