### ISSUE TITLE
网络结构

### ISSUE THREAD

**Issue by henbucuoshanghai** [luminxu/ViPNAS#5]
训练的时候t，t+1，t+2帧网络结构不一样？测试的时候呢？
backbone的代码在哪里呢？
tks

**Comment by luminxu** [comment]
和其他方法一样，ViPNAS在训练和测试时网络结构的设置不会发生改变。T-ViPNAS在训练和测试时均不同帧使用不同网络结构。
当前repo在MMPose的代码框架下复现了基于图像的人体姿态估计网络S-ViPNAS（请参考[此处](https://github.com/luminxu/ViPNAS/issues/4)），backbone代码可参见该[文件](https://github.com/luminxu/ViPNAS/blob/main/mmpose/models/backbones/vipnas_resnet.py)。
