### ISSUE TITLE
where is constraints C in the code

### ISSUE THREAD

**Issue by DongHappyyy** [luminxu/ViPNAS#9]
Excuse me, I'm back again. I want to ask where the computation complexity (Flops) constraints C in the paper is in the code. I tried to find this constraint C, but I didn't find it

**Comment by luminxu** [comment]
The computational complexity constraint is set in the search process. We can find a best architecture under the constraint via neural architecture search. However, we directly release the discovered optimal architecture in the codes, where the computational complexity constraint is not needed.
